### PR TITLE
Added BinarySearch

### LINKED ISSUE #19: Add Binary Search
[Binary Search](https://en.wikipedia.org/wiki/Binary_search_algorithm)
Want to work on this issue : Yes  
JAVA

### PR DESCRIPTION
**Pull request by TarunISCO**
Fixes #19

### CODE REVIEW

**Comment by ashu-beckham** [comment]
@TarunISCO Add in another language except java. I have already Added it in java.

**Comment by TarunISCO** [comment]
@ashu-beckham where?

**Comment by ashu-beckham** [comment]
@TarunISCO See the master branch

**Comment by TarunISCO** [comment]
but you assigned me. that's why I was working on this.
and please mention the issue number in pr description.

**Comment by ashu-beckham** [comment]
If possible change the code into python .I will be good to add variety of codes in the repository .otherwise leave it. After that u can close this pr.

**Comment by TarunISCO** [comment]
Okay. We can add for both python and c/c++.

**Comment by TarunISCO** [comment]
should we add some new contributors to these tasks? It will be good for new contributors.

**Comment by ashu-beckham** [comment]
ok . But not too much. Everyone should know all the algos in the repo . Smaller the group ,the better.

**Pull request merged**
