### PR TITLE
Added QuickSort

### PR DESCRIPTION
**Pull request by TarunISCO**

### CODE REVIEW

**Comment by TarunISCO** [comment]
@ashu-beckham review.

**Comment by ashu-beckham** [comment]
@TarunISCO  fix codeclimate issues.

**Comment by TarunISCO** [comment]
@ashu-beckham please remove your commit in this pr.
I'm already updating this.

**Comment by ashu-beckham** [comment]
ok

**Comment by ashu-beckham** [comment]
I have removed the issues and merged.

**Pull request merged**
